# Generated by Django 3.2.8 on 2021-10-17 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlebooksearch_app', '0002_auto_20211017_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
