# Generated by Django 3.2.8 on 2021-10-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlebooksearch_app', '0004_auto_20211017_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
