# Generated by Django 3.2.8 on 2021-10-17 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlebooksearch_app', '0005_alter_book_pages_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
